apiVersion: v1
kind: Service
metadata:
  name: bpmn
  labels:
    app: bpmn
    group: iot
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: bpmn
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: bpmn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpmn
  template:
    metadata:
      labels:
        app: bpmn
        group: customer
        tier: frontend
    spec:
      containers:
      - name: bpmn
        image: smokja/bpmn        
        ports:
        - containerPort: 80
          name: bpmn