apiVersion: v1
kind: Service
metadata:
  name: bpmn-camunda
  labels:
    app: bpmn-camunda
    group: iot
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: bpmn-camunda
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: bpmn-camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpmn-camunda
  template:
    metadata:
      labels:
        app: bpmn-camunda
        group: customer
        tier: frontend
    spec:
      containers:
      - name: bpmn-camunda
        image: camunda/camunda-bpm-platform:latest  
        ports:
        - containerPort: 8080
          name: bpmn-camunda
        
        
      